version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      otel:
        patterns:
        - "go.opentelemetry.io/*"
        - "github.com/open-telemetry/*"
  # go tools
  - package-ecosystem: "gomod"
    directory: "tools/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"
